#!/bin/sh

. ./setup
. ./common

make clean

SUITE_DIR=$SUITES_DIR/$1

echo Cleaning suite $1.

echo removing outputs
rm -f  $SUITE_DIR/$OUTPUT_DIR/*

echo removing autogenerated expected outputs
for g in $(ls $SUITE_DIR/$EXPECTED_DIR/*.gen 2> /dev/null )
do
	filename=$(basename $g)
	rm -f $SUITE_DIR/$EXPECTED_DIR/${filename%.gen}.out
	rm -f $SUITE_DIR/$EXPECTED_DIR/${filename%.gen}.err
done
